import io
import re
import sys
import textwrap
import zipfile

from flask import current_app, flash, redirect, render_template, request, send_file
from PIL import Image

from app.core import bp
from app.core.utils import allowed_file, get_download_count, increment_download_count


@bp.route("/favicon.ico")
def favicon():
    return redirect("/vercel.svg", code=307)


@bp.route("/", methods=["GET", "POST"])
def index():
    # Always get current count for display
    download_count = get_download_count()

    if request.method == "POST":
        if "file" not in request.files:
            flash("No file part", "red")
            return render_template("core/index.j2", download_count=download_count)

        file = request.files.get("file")

        if file.filename == "":
            flash("No selected file", "red")
            return render_template("core/index.j2", download_count=download_count)

        # Check app name
        app_name = request.form.get("app_name", "splunk_app").strip()

        # Sanitize app name for filename (alphanumeric, underscores, hyphens only)
        safe_app_name = re.sub(r"[^a-zA-Z0-9_\-]", "_", app_name)
        if not safe_app_name:
            safe_app_name = "splunk_app"

        if file and allowed_file(file.filename):
            try:
                # 1. Open and convert image
                image = Image.open(file.stream)
                image = image.convert("RGBA")

                # 2. Prepare in-memory ZIP
                zip_buffer = io.BytesIO()

                with zipfile.ZipFile(
                    zip_buffer, "a", zipfile.ZIP_DEFLATED, False
                ) as zip_file:
                    # 3. Generate icons
                    for spec in current_app.config.get("ICON_SPECS"):
                        target_size = spec.get("size")
                        mode = spec.get("resize_mode", "force")

                        if mode == "fit":
                            # 'fit' mode: Resize to fit WITHIN target_size, preserving aspect ratio.
                            # We copy the image because thumbnail modifies in-place.
                            processed_img = image.copy()
                            processed_img.thumbnail(
                                target_size, Image.Resampling.LANCZOS
                            )
                        else:
                            # 'force' mode: Force exact dimensions (standard for square icons)
                            processed_img = image.resize(
                                target_size, Image.Resampling.LANCZOS
                            )

                        img_buffer = io.BytesIO()
                        processed_img.save(img_buffer, format="PNG", optimize=True)

                        zip_file.writestr(spec.get("name"), img_buffer.getvalue())

                    # 4. Add README.txt with instructions
                    instructions = textwrap.dedent(
                        """
                            Splunk App Icon Installation
                            ============================

                            App Name: {safe_app_name}

                            Installation Steps:
                            1. Extract the contents of this zip file.
                            2. Place the images in your Splunk app's static directory:
                               $SPLUNK_HOME/etc/apps/{safe_app_name}/static/

                               (Note: If the 'static' directory does not exist, create it: 'mkdir -p $SPLUNK_HOME/etc/apps/{safe_app_name}/static/')

                            3. To see the changes:
                               - Restart Splunk, OR
                               - Clear the Splunk web cache by visiting: http://<splunk-host>:8000/en-US/_bump

                            Generated by Splunk Icon Generator
                        """
                    ).format(safe_app_name=safe_app_name)

                    zip_file.writestr("README.txt", instructions)

                # 5. Increment Counter
                increment_download_count()

                # 6. Finalize
                zip_buffer.seek(0)

                return send_file(
                    zip_buffer,
                    mimetype="application/zip",
                    as_attachment=True,
                    download_name=f"{safe_app_name}_splunk_icons.zip",
                )

            except Exception as e:
                print(f"Error processing image: {str(e)}", file=sys.stderr)
                flash(f"Error processing image: {str(e)}", "red")
                return render_template("core/index.j2", download_count=download_count)

    return render_template("core/index.j2", download_count=download_count)
